# Generated by Django 4.2 on 2025-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_variant_product_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sku',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='SKU'),
        ),
    ]
