# Generated by Django 4.2 on 2025-05-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_category_sku_alter_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sku'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku'], 'verbose_name_plural': 'Products'},
        ),
    ]
