# Generated by Django 4.2 on 2025-06-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_category_image_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='variant_type',
            field=models.CharField(choices=[('specification', 'Specification'), ('size', 'Size'), ('length', 'Length'), ('model', 'Model')], default='specification', max_length=32, verbose_name='Variant Type'),
        ),
    ]
