# Generated by Django 4.2 on 2025-06-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_variant_variant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='color',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='color',
            new_name='model',
        ),
    ]
