# Generated by Django 4.2 on 2025-06-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_color_cart_model_rename_color_orderitem_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('received', 'Приета'), ('shipped', 'Изпратена'), ('delivered', 'Доставена'), ('completed', 'Завършена'), ('canceled', 'Отказана')], default='received', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PayPal', 'PayPal'), ('Stripe', 'Stripe'), ('Flutterwave', 'Flutterwave'), ('Paystack', 'Paystack'), ('RazorPay', 'RazorPay'), ('cash_on_delivery', 'Наложен платеж')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Платено'), ('cash_on_delivery', 'Наложен платеж'), ('failed', 'Неуспешно плащане')], default='cash_on_delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('received', 'Приета'), ('shipped', 'Изпратена'), ('delivered', 'Доставена'), ('completed', 'Завършена'), ('canceled', 'Отказана')], default='received', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_service',
            field=models.CharField(blank=True, choices=[('Econt', 'Еконт'), ('Speedy', 'Спиди'), ('UPS', 'UPS'), ('GIG Logistics', 'GIG Logistics')], default=None, max_length=100, null=True),
        ),
    ]
