# Generated by Django 4.2 on 2025-06-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_orderitem_vendor_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_service',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, choices=[('Econt', 'Еконт'), ('Speedy', 'Спиди'), ('UPS', 'UPS'), ('GIG Logistics', 'GIG Logistics')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
