# Generated by Django 4.2 on 2025-06-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_orderitem_shipping_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='initial_total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
