# Generated by Django 4.2 on 2025-06-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_cart_shipping_remove_cart_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
