# Generated by Django 4.2 on 2025-06-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'карта'), ('cash_on_delivery', 'Наложен платеж')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('processing', 'Обработка'), ('paid', 'Платено'), ('failed', 'Неуспешно плащане'), ('cash_on_delivery', 'Наложен платеж')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, choices=[('econt', 'Еконт'), ('speedy', 'Спиди')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='Published', max_length=50),
        ),
    ]
