# Generated by Django 4.2 on 2025-07-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_category_meta_description_category_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hover_image',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Втора снимка (показва се при задържане)'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярна категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='marketing_image',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Маркетинг снимка'),
        ),
    ]
