# Generated by Django 4.2 on 2025-07-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_category_hover_image_category_is_popular_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='initial_total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='applied_coupon',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_status',
        ),
    ]
