# Generated by Django 4.2 on 2025-07-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_orderitem_options_remove_order_initial_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Stats',
                'verbose_name_plural': 'Stats',
                'managed': False,
            },
        ),
    ]
