# Generated by Django 4.2 on 2025-07-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_colorgroup_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#000000', max_length=7),
            preserve_default=False,
        ),
    ]
