# Generated by Django 4.2 on 2025-08-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_gallery_product_alter_orderitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
        # Rename previous sale field to sale_price
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="sale_price",
        ),
        # Rename regular_price to price (base price)
        migrations.RenameField(
            model_name="product",
            old_name="regular_price",
            new_name="price",
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False, db_index=True),
        ),
    ]