# Generated by Django 4.2 on 2025-08-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_price_refactor_add_on_sale_delete_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='BandOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_deals', to='store.product')),
            ],
            options={
                'verbose_name': 'Band of the Day',
                'verbose_name_plural': 'Band of the Day',
                'ordering': ['-date'],
            },
        ),
    ]