# Generated by Django 4.2 on 2025-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_bandoftheday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('initiated', 'Незавършена'), ('received', 'Приета'), ('shipped', 'Изпратена'), ('delivered', 'Доставена'), ('completed', 'Завършена'), ('canceled', 'Отказана')], default='initiated', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled')], default='published', max_length=50),
        ),
    ]
