# Generated by Django 4.2 on 2025-08-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_order_order_status_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SizeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sizes', models.ManyToManyField(blank=True, related_name='size_groups', to='store.size')),
            ],
            options={
                'verbose_name': 'Size group',
                'verbose_name_plural': 'Size groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use product price/sale logic', max_digits=12, null=True)),
                ('device_models', models.ManyToManyField(blank=True, related_name='product_items', to='store.devicemodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='store.size')),
            ],
            options={
                'verbose_name': 'Product item (SKU)',
                'verbose_name_plural': 'Product items (SKUs)',
            },
        ),
        migrations.CreateModel(
            name='ModelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('generate_as_single_sku', models.BooleanField(default=False, help_text='When true, SKU generation will create one SKU per size and attach all models in this group to it.')),
                ('device_models', models.ManyToManyField(blank=True, related_name='model_groups', to='store.devicemodel')),
            ],
            options={
                'verbose_name': 'Model group',
                'verbose_name_plural': 'Model groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='model_groups',
            field=models.ManyToManyField(blank=True, help_text='Select one or more groups of compatible device models', related_name='products', to='store.modelgroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.sizegroup'),
        ),
        migrations.AddIndex(
            model_name='productitem',
            index=models.Index(fields=['product'], name='store_produ_product_95e101_idx'),
        ),
        migrations.AddIndex(
            model_name='productitem',
            index=models.Index(fields=['product', 'size'], name='store_produ_product_a7e46e_idx'),
        ),
    ]
