# Generated by Django 4.2 on 2025-08-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_devicemodel_size_sizegroup_productitem_modelgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='price_override',
        ),
        migrations.AddField(
            model_name='productitem',
            name='price_delta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional delta to add to product price/sale price (e.g., 3.00)', max_digits=12, null=True),
        ),
    ]
