# Generated by Django 4.2 on 2025-09-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_remove_productitem_price_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, help_text='Optional extra categories where this product should also appear', related_name='extra_products', to='store.category'),
        ),
        migrations.CreateModel(
            name='CategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_parents', to='store.category')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_children', to='store.category')),
            ],
            options={
                'verbose_name': 'Category link (alias)',
                'verbose_name_plural': 'Category links (aliases)',
            },
        ),
        migrations.AddConstraint(
            model_name='categorylink',
            constraint=models.CheckConstraint(check=models.Q(('parent', models.F('child')), _negated=True), name='catlink_parent_not_child'),
        ),
        migrations.AlterUniqueTogether(
            name='categorylink',
            unique_together={('parent', 'child')},
        ),
    ]
