# Generated by Django 4.2 on 2025-09-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_product_additional_categories_categorylink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant_type',
            field=models.CharField(choices=[('specification', 'Specification'), ('length', 'Length')], default='specification', max_length=32, verbose_name='Variant Type'),
        ),
    ]
