# Generated by Django 4.2 on 2025-09-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_remove_category_image_alter_variant_variant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='h1_override',
            field=models.CharField(blank=True, help_text='When set, this will replace the dynamic product detail H1', max_length=150, null=True),
        ),
    ]
