# Generated by Django 4.2 on 2025-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_band_of_the_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_banner',
            field=models.BooleanField(default=True, verbose_name='Показвай банера в категория'),
        ),
    ]
