# Generated by Django 4.2 on 2025-10-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_category_show_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_buy_qty',
            field=models.PositiveIntegerField(default=0, help_text="X in 'Buy X Get Y Free'."),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_get_qty',
            field=models.PositiveIntegerField(default=0, help_text="Y in 'Buy X Get Y Free'."),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_label_override',
            field=models.CharField(blank=True, help_text='Optional custom label for the promotion badge.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_type',
            field=models.CharField(choices=[('none', 'No promotion'), ('buy_x_get_y', 'Buy X Get Y Free')], db_index=True, default='none', help_text='Type of product-level promotion.', max_length=20),
        ),
    ]
