# Generated by Django 4.2 on 2025-10-26 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0048_product_promo_buy_qty_product_promo_get_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_spins', models.PositiveIntegerField(db_index=True, help_text='Award triggers when user reaches this total spin count')),
                ('prize_type', models.CharField(choices=[('none', 'No prize'), ('discount_percent', 'Percentage discount'), ('free_shipping', 'Free shipping'), ('mystery_box_min_total', 'Mystery box over minimum total')], default='none', max_length=32)),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('min_order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('label', models.CharField(default='Награда за лоялност', max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['threshold_spins', 'id'],
                'unique_together': {('threshold_spins', 'prize_type', 'discount_percent', 'min_order_total')},
            },
        ),
        migrations.CreateModel(
            name='SpinPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('prize_type', models.CharField(choices=[('none', 'No prize'), ('discount_percent', 'Percentage discount'), ('free_shipping', 'Free shipping'), ('mystery_box_min_total', 'Mystery box over minimum total')], db_index=True, default='none', max_length=32)),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('min_order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weight', models.FloatField(default=0.0, help_text='Relative probability weight; higher means more likely.')),
                ('color', models.CharField(blank=True, help_text='Slice color hex code (e.g., #FFE082)', max_length=7, null=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Spin prize',
                'verbose_name_plural': 'Spin prizes',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpinMilestoneAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='store.spinmilestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_milestone_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'milestone')},
            },
        ),
        migrations.CreateModel(
            name='SpinEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('result_label', models.CharField(max_length=64)),
                ('prize_type', models.CharField(choices=[('none', 'No prize'), ('discount_percent', 'Percentage discount'), ('free_shipping', 'Free shipping'), ('mystery_box_min_total', 'Mystery box over minimum total')], db_index=True, default='none', max_length=32)),
                ('coupon_discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('free_shipping', models.BooleanField(default=False)),
                ('min_order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coupon_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily spin entry',
                'verbose_name_plural': 'Daily spin entries',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
