# Generated by Django 4.2 on 2025-11-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_modelgroup_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_campaign', models.CharField(choices=[('default', 'Default'), ('halloween', 'Halloween'), ('black-friday', 'Black Friday')], db_index=True, default='default', max_length=32)),
            ],
            options={
                'verbose_name': 'Store theme settings',
                'verbose_name_plural': 'Store theme settings',
            },
        ),
    ]
