# Generated by Django 4.2 on 2026-01-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_storethemesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='h1_override',
            field=models.CharField(blank=True, help_text='When set, this will replace the dynamic product detail H1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
