# Generated by Django 4.2 on 2024-12-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Customer Addresses'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('econt', 'Econt'), ('speedy', 'Speedy'), ('personal', 'Personal')], max_length=10, null=True),
        ),
    ]
