# Generated by Django 4.2 on 2024-12-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_address_options_remove_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('econt', 'Еконт'), ('speedy', 'Спиди'), ('personal', 'Личен адрес')], max_length=10, null=True),
        ),
    ]
