# Generated by Django 4.2 on 2025-06-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_address_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('econt', 'Еконт'), ('econt_box', 'Еконтомат'), ('speedy', 'Спиди'), ('speedy_box', 'Спидомат'), ('personal', 'Личен адрес')], max_length=10, null=True),
        ),
    ]
