# Generated by Django 4.2 on 2025-07-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_address_delivery_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основен адрес'),
        ),
        migrations.AlterField(
            model_name='address',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('econt_office', 'Еконт офис'), ('econt', 'Еконт адрес'), ('speedy_office', 'Спиди офис'), ('speedy', 'Спиди адрес')], max_length=16, null=True),
        ),
    ]
