# Generated by Django 4.2 on 2025-07-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_full_name_address_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='office_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='office_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
