# Generated by Django 4.2 on 2025-07-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_address_office_code_address_office_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='face',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
